### ISSUE TITLE
Please add url to the product page

### ISSUE THREAD

**Issue by dignityinside** [rg3/steam_discounts#1]
Will be cool when you add a link to product page...

Something like that:

Farmer's Dynasty ...........................  26,99€ [ 29,99€ -10%]
http://store.steampowered.com/app/678900/Farmers_Dynasty/

Finding Paradise ...........................   8,99€ [  9,99€ -10%]
http://store.steampowered.com/app/337340/Finding_Paradise/

Gang Beasts ................................  15,99€ [ 19,99€ -20%]
http://store.steampowered.com/app/285900/Gang_Beasts/

**Comment by rg3** [comment]
Excellent idea. Added.
